jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - script: build-and-test.cmd
  - script: src\create-package.cmd
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: artifacts/packages/Release
      artifactName: packages
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: ./build-and-test.sh
