phases:
- phase: Windows
  queue: Hosted VS2017
  steps:
  - task: CmdLine@1
    displayName: Run build-and-test.cmd
    inputs:
      filename: 'build-and-test.cmd'
- phase: Linux
  queue: Hosted Linux Preview
  steps:
  - task: CmdLine@1
    displayName: Run build-and-test.sh
    inputs:
      filename: './build-and-test.sh'
